# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AliumUIKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'alium_sdk', :path => '../'
  # Pods for AliumUIKitExample

  target 'AliumUIKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AliumUIKitExampleUITests' do
    # Pods for testing
  end

end
