# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AliumSwiftUIExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'alium_sdk', :path => '../'

  # Pods for AliumSwiftUIExample

  target 'AliumSwiftUIExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AliumSwiftUIExampleUITests' do
    # Pods for testing
  end

end
